models:
  winning_criteria_binary_classifier: ../models/winning_criteria_binary_classifier
  default_llm_model: VAGOsolutions/SauerkrautLM-Mixtral-8x7B-Instruct
paths:
  output_path_relevance_criteria: ../model_outputs/automatically_detected_examples_with_criteria/
  output_path_procurement_analyzer: ../model_outputs/procurement_analyzer/
  logs: ../logs
  s3_credentials: ./s3_bucket_credentials.json
procurement_analyzer:
  languages: 
    - de
  components:
    relevance_classifier: True
    award_criteria_extraction: True
    regex: False
    regex_pattern: superkalifragilistikexpialigetisch
  context_window: 1
  max_number_of_documents: 100000000
prompts:
  award_criteria_extraction:
    prompt_4